### ISSUE TITLE
View as Student doesn't work with Flashcards

### ISSUE THREAD

**Issue by bilbe** [Harvard-ATG/HarvardCards#160]
View as Student doesn't work with Flashcards or at least it doesn't display the list any differently.
![screen shot 2015-09-16 at 10 26 41 am](https://cloud.githubusercontent.com/assets/5712116/9907538/a3e5d67c-5c5d-11e5-8f4d-cd9415615c31.png)

**Comment by arthurian** [comment]
This has been resolved, I believe. Closing for now (can be re-opened if needed).
